[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "smll"
authors = [{name = "Gama Sibusiso", email = "mfanakagama@gmail.com"}]
dynamic = ["version", "description"]
